### ISSUE TITLE
Top player inventory row not visible in crafting bench

### ISSUE THREAD

**Issue by tacotexmex** [rubenwardy/crafting#22]
Something happened with the top player inventory row in crafting when using the crafting bench and similar stations. It's still visible in the sfinv tab but not in stations. Take a look at [this clip](https://imgur.com/a/zprm1jT) (sfinv tab first, station second)

What could be causing this?

I've tried it both in 0.4.17.1 and in 0.5.0-dev with the same results.

**Comment by LoneWolfHT** [comment]
https://github.com/rubenwardy/crafting/pull/25
